# Generated by Django 5.0 on 2023-12-17 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_student_balance_alter_student_points_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistant',
            name='national_ID_photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='assistant',
            name='personal_photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='national_ID_photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='personal_photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
