# Generated by Django 5.0 on 2023-12-17 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_teacher_accepted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='accepted',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
