# Generated by Django 5.0 on 2023-12-18 07:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_attachment_attachment_path_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assistant',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='student',
            name='birth_date',
        ),
        migrations.AddField(
            model_name='user',
            name='birth_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
