# Generated by Django 5.0 on 2023-12-18 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_assistant_birth_date_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lecture',
            unique_together={('lecture_title', 'course')},
        ),
    ]
