# Generated by Django 5.0 on 2023-12-18 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_lecture_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachrequest',
            name='date_reviewed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
