# Generated by Django 5.0 on 2023-12-19 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_course_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='lecture',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.lecture'),
        ),
        migrations.AlterField(
            model_name='assistant',
            name='national_ID_photo',
            field=models.ImageField(upload_to='assistants/national_IDs/'),
        ),
        migrations.AlterField(
            model_name='assistant',
            name='personal_photo',
            field=models.ImageField(upload_to='assistants/personal_photos/'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='attachment',
            field=models.FileField(max_length=250, null=True, upload_to='lectures/attachments/'),
        ),
        migrations.AlterField(
            model_name='course',
            name='thumbnail',
            field=models.ImageField(upload_to='courses/courses_thumbnails/'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='lecture',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.lecture'),
        ),
        migrations.AlterField(
            model_name='student',
            name='personal_photo',
            field=models.ImageField(blank=True, null=True, upload_to='students/personal_photos/'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='national_ID_photo',
            field=models.ImageField(upload_to='teachers/national_IDs/'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='personal_photo',
            field=models.ImageField(upload_to='teachers/personal_photos/'),
        ),
    ]
