# Generated by Django 5.0 on 2023-12-19 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_assignment_lecture_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pointstransaction',
            old_name='student_id',
            new_name='student',
        ),
        migrations.RenameField(
            model_name='studentbalancetransaction',
            old_name='student_id',
            new_name='student',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='payment_date',
        ),
        migrations.AddField(
            model_name='pointstransaction',
            name='payment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='api.payment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentbalancetransaction',
            name='payment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='api.payment'),
            preserve_default=False,
        ),
    ]
