# Generated by Django 5.0 on 2023-12-19 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_rename_student_id_pointstransaction_student_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='academic_year',
            field=models.CharField(choices=[(1, 'Junior 1'), (2, 'Junior 2'), (3, 'Junior 3'), (4, 'Junior 4'), (5, 'Junior 5'), (6, 'Junior 6'), (7, 'Middle 1'), (8, 'Middle 2'), (9, 'Middle 3'), (10, 'Senior 1'), (11, 'Senior 2'), (12, 'Senior 3')], max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='payment',
            unique_together={('student', 'lecture')},
        ),
    ]
