# Generated by Django 5.0 on 2023-12-19 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_paymentmethod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointstransaction',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.payment'),
        ),
        migrations.AlterField(
            model_name='pointstransaction',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.student'),
        ),
        migrations.AlterField(
            model_name='studentbalancetransaction',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.payment'),
        ),
        migrations.AlterField(
            model_name='studentbalancetransaction',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.student'),
        ),
    ]
