from django.contrib import admin
from .models import *

admin.site.register(Notification)
admin.site.register(TeacherBalanceTransaction)
admin.site.register(Badge)
admin.site.register(BadgeEarning)
admin.site.register(Teaching)
admin.site.register(TeacherRating)
admin.site.register(AssistanceRequest)
admin.site.register(AssistantRating)
admin.site.register(Warnings)
admin.site.register(Attachment)
admin.site.register(Quiz)
admin.site.register(Assignment)
admin.site.register(QA)
admin.site.register(QAAnswer)
admin.site.register(Upvote)
admin.site.register(QuizHandIn)
admin.site.register(QuizQuestion)
admin.site.register(QuizQuestionChoice)
admin.site.register(QuizQuestionAnswer)
admin.site.register(AssignmentQuestion)
admin.site.register(AssignmentQuestionChoice)
admin.site.register(AssignmentQuestionAnswer)
admin.site.register(AssignmentHandIn)