from django.contrib import admin
from .models import *

admin.site.register(UsersRole)
admin.site.register(User)
admin.site.register(Notification)
admin.site.register(Student)
admin.site.register(Teacher)
admin.site.register(TeachRequest)
admin.site.register(TeacherBalanceTransaction)
admin.site.register(Assistant)
admin.site.register(Subject)
admin.site.register(Course)
admin.site.register(Enrollment)
admin.site.register(PointsTransaction)
admin.site.register(StudentBalanceTransaction)
admin.site.register(Badge)
admin.site.register(BadgeEarning)
admin.site.register(Teaching)
admin.site.register(TeacherRating)
admin.site.register(AssistanceRequest)
admin.site.register(AssistantRating)
admin.site.register(CourseRating)
admin.site.register(Lecture)
admin.site.register(Warnings)
admin.site.register(Attachment)
admin.site.register(Payment)